"""Shared matplotlib style configuration for publication-quality figures.

Provides consistent colors, fonts, and helper functions used by every figure
module in the visualization package.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.figure import Figure

# ---------------------------------------------------------------------------
# Color palette
# ---------------------------------------------------------------------------

# IBM Design / Wong colorblind-safe palette for accessibility
COLORS: Dict[str, str] = {
    "primary": "#2563EB",
    "secondary": "#059669",
    "accent": "#DC2626",
    "warning": "#D97706",
    "neutral": "#6B7280",
    "background": "#F9FAFB",
}

PALETTE: List[str] = [
    "#2563EB",  # blue
    "#DC2626",  # red
    "#059669",  # green
    "#D97706",  # amber
    "#7C3AED",  # violet
    "#DB2777",  # pink
    "#0891B2",  # cyan
    "#65A30D",  # lime
]

FONTSIZE: Dict[str, int] = {
    "tiny": 8,
    "small": 10,
    "note": 11,
    "base": 12,
    "large": 14,
    "title": 16,
}

# Semantic color mapping for consistency across figures
# Uses IBM Design / Wong colorblind-safe palette
SEMANTIC_COLORS: Dict[str, str] = {
    # System components
    "user": "#4A90D9",        # Sky Blue
    "firewall": "#648FFF",    # IBM Blue (Distinct from User)
    "orchestrator": "#27AE60", # Green
    "agent": "#9B59B6",       # Purple
    "external": "#E74C3C",    # Red
    "attack": "#C0392B",      # Dark Red

    # Taxonomy / Layers (Aliases for coherence)
    "peripheral": "#E74C3C",  # Red (Same as external tools)
    "coordination": "#FFB000", # Gold (Distinct from others)
    "systemic": "#27AE60",    # Green (Same as orchestrator)

    # Defense configurations
    "baseline": "#999999",    # Gray
    "sandbox": "#785EF0",     # IBM Purple
    "tripwire": "#DC267F",    # IBM Magenta
    "full_cif": "#FE6100",    # IBM Orange
    "invariants": "#FFB000",  # IBM Gold
    "anomaly": "#FFB000",     # IBM Gold (alias for invariants/anomaly)

    # General status
    "good": "#059669",        # Green
    "bad": "#DC2626",         # Red
    "neutral": "#6B7280",     # Gray
}


# ---------------------------------------------------------------------------
# Style application
# ---------------------------------------------------------------------------

def apply_style() -> None:
    """Configure matplotlib rcParams for publication-quality output."""
    matplotlib.rcParams.update({
        "font.family": "sans-serif", # Switch to sans-serif for better screen/digital reading
        "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica"],
        "font.size": 12,
        "axes.labelsize": 14,
        "axes.titlesize": 16,
        "figure.dpi": 300,
        "savefig.dpi": 300,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.framealpha": 0.95,
        "legend.edgecolor": "0.8",
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "legend.fontsize": 11,
    })


# ---------------------------------------------------------------------------
# Figure creation helpers
# ---------------------------------------------------------------------------

def create_figure(
    width: float = 6.5,
    height: float = 4.5,
    n_rows: int = 1,
    n_cols: int = 1,
) -> Tuple[Figure, Union[Axes, "numpy.ndarray"]]:
    """Create a styled figure with the given grid layout.

    Returns
    -------
    fig : Figure
    axes : Axes or ndarray of Axes
    """
    apply_style()
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(width, height))
    fig.patch.set_facecolor(COLORS["background"])
    return fig, axes


def add_source_annotation(fig: Figure, source_file: str) -> None:
    """Add a small annotation showing the generating script path.

    Places italic text at the bottom of the figure so that each rendered
    figure is permanently linked to the script that produced it.
    """
    fig.text(
        0.99,
        0.01,
        f"Generated by: {source_file}",
        ha="right",
        va="bottom",
        fontsize=7,
        fontstyle="italic",
        color="#999999",
        transform=fig.transFigure,
    )



def save_figure(
    fig: Figure,
    name: str,
    output_dir: str = "output/figures",
    formats: Sequence[str] = ("pdf", "png"),
) -> List[str]:
    """Save *fig* in multiple formats and return the list of saved paths."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    saved: List[str] = []
    for fmt in formats:
        path = out / f"{name}.{fmt}"
        fig.savefig(str(path), format=fmt)
        saved.append(str(path))
    plt.close(fig)
    return saved


def format_axis(
    ax: Axes,
    xlabel: str,
    ylabel: str,
    title: Optional[str] = None,
) -> None:
    """Apply standard axis labels and optional title."""
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if title is not None:
        ax.set_title(title)


def add_legend(ax: Axes, loc: str = "best", **kwargs) -> None:
    """Add a consistently-styled legend to *ax*."""
    ax.legend(
        loc=loc,
        framealpha=0.9,
        edgecolor="0.8",
        fontsize=FONTSIZE["base"],
        **kwargs,
    )
